export type EmployeeLevel = 'Junior' | 'Mid' | 'Senior' | 'Lead';

export interface Employee {
  id: string;
  name: string;
  email: string;
  department: string;
  role: string;
  location: string;
  level: EmployeeLevel;
}

// Payload for create (id typically generated by server)
export type CreateEmployeeRequest = Omit<Employee, 'id'>;

export interface EmployeesQueryState {
  pageIndex: number;
  pageSize: number;
  search: string;
}
